apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: cilium
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: cilium
      repoURL: 'https://helm.cilium.io/'
      targetRevision: 1.18.5
      helm:
        valueFiles:
        - $values/terraform/files/cilium.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  # syncPolicy:
  #   automated:
  #     selfHeal: true