apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: heimdall-ext
  namespace: istio-ingress
spec:
  hosts:
  - "heimdall.local.xuhuisun.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  endpoints:
  - address: 192.168.60.241
    ports:
      https: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: heimdall-vs
  namespace: istio-ingress
spec:
  hosts:
  - "local.xuhuisun.com"
  - "heimdall.local.xuhuisun.com"
  gateways:
  - gateway
  http:
  - timeout: 3s
    route:
    - destination:
        host: "heimdall.local.xuhuisun.com"
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: heimdall
  namespace: istio-ingress
spec:
  host: "heimdall.local.xuhuisun.com"
  trafficPolicy:
    tls:
      mode: DISABLE
