apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: aistor-s3-vs
  namespace: primary-object-store
spec:
  hosts:
  - aistor.local.xuhuisun.com
  gateways:
  - istio-ingress/gateway
  tcp:
  - match:
    - port: 443
    route:
    - destination:
        host: minio
        port:
          number: 443
      weight: 100