apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: immich-vs
  namespace: immich 
spec:
  hosts:
  - "immich.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: immich-immich-server
        port:
          number: 2283