apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: cert-manager
      repoURL: 'https://charts.jetstack.io'
      targetRevision: v1.17.0
      helm:
        valueFiles:
        - $values/cert-manager/values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
