apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: openebs
  namespace: argocd
spec:
  project: default
  destination:
    namespace: openebs
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: openebs
      repoURL: 'https://openebs.github.io/charts'
      targetRevision: 3.10.0
      helm:
        valueFiles:
        - $values/openebs/values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
