apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "70"
  name: lgtm-distributed
  namespace: argocd
spec:
  project: default
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: lgtm-distributed
      repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: 2.1.0
      helm:
        valueFiles:
        - $values/lgtm-distributed/values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
