apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: argocd-vs
  namespace: argocd
spec:
  hosts:
  - "argocd.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: argocd-server
        port:
          number: 443
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: argocd-dr
  namespace: argocd
spec:
  host: argocd-server
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
