apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  name: jaeger
  namespace: argocd
spec:
  project: default
  destination:
    namespace: observability
    server: 'https://kubernetes.default.svc'
  source:
    path: jaeger/jaeger
    repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
