apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  name: kafka
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kafka
    server: 'https://kubernetes.default.svc'
  source:
    path: strimzi/kafka
    repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
