apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "80"
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: argo-cd
      repoURL: 'https://argoproj.github.io/argo-helm'
      targetRevision: 7.8.9
      helm:
        valueFiles:
        - $values/argocd/values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
