apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  name: open-webui
  namespace: argocd
spec:
  project: default
  destination:
    namespace: open-webui
    server: 'https://kubernetes.default.svc'
  source:
    path: open-webui/argocd
    repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
