type: postgresql
version:
  postgresql: "17"
# mode: recovery

# recovery:
#   method: object_store
#   clusterName: n8n-cnpg-cluster
#   database: n8n
#   endpointURL: https://s3.local.xuhuisun.com
  # endpointCA:
  #   create: true
    # value: |
    #   LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRUmo3QWFjUUFK
    #   d0VKeTJiWGFNKzMvakFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxk
    #   R1Z6TUI0WERUSTFNRGd4TnpBd01qazFNRm9YRFRNMU1EZ3hOVEF3TWprMQpNRm93RlRFVE1CRUdB
    #   MVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFC
    #   TEFGYnN5VGlFQ2l5dTl3ZkwrRHlrQ1ozSXI3eWhTSExUUHhWU2pFWFhaZDBzVXZKLzZ0UnZJZW92
    #   ZjIKRnVib2NEb2dqMGxWQVVuVXVIWncyaityd0pXallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hE
    #   QWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JB
    #   VXdBd0VCL3pBZEJnTlZIUTRFCkZnUVU3VTNBeDkwUjlyalhjd1pnQk9qbTRrbjE3UUV3Q2dZSUtv
    #   Wkl6ajBFQXdJRFNBQXdSUUloQUxCMDVjaTgKMThWaitreDg2cUp6bTdvU0Ivb3l5UDBSN0hrMDR1
    #   Y1ovSTR6QWlBUm1EVnJhZ1RITEF3bGNkaUZQMW10SmpoZwpEdU9iOVlOczRRbTQ0UEpRYXc9PQot
    #   LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCgo=
#   provider: s3
#   s3:
#     bucket: cloudnative-pg-backups
#     accessKey: om9WSI45aMEZxBqASwSy
#     secretKey: f31Tff9m6TaPJRhZ45GjO0HUxzx4yM8HmQ7xCnAJ

cluster:
  instances: 3
  storage:
    size: 4Gi
    storageClass: proxmox-local-zfs-xfs
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 100m
      memory: 1Gi
  affinity:
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  monitoring:
    enabled: true
    podMonitor:
      enabled: true
    prometheusRule:
      enabled: false
  postgresql:
    parameters:
      shared_buffers: 256MB
  initdb:
    database: n8n

backups:
  enabled: true
  endpointURL: https://minio.primary-object-store.svc.cluster.local
  endpointCA:
    create: true
    value: |
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRUmo3QWFjUUFK
      d0VKeTJiWGFNKzMvakFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxk
      R1Z6TUI0WERUSTFNRGd4TnpBd01qazFNRm9YRFRNMU1EZ3hOVEF3TWprMQpNRm93RlRFVE1CRUdB
      MVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFC
      TEFGYnN5VGlFQ2l5dTl3ZkwrRHlrQ1ozSXI3eWhTSExUUHhWU2pFWFhaZDBzVXZKLzZ0UnZJZW92
      ZjIKRnVib2NEb2dqMGxWQVVuVXVIWncyaityd0pXallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hE
      QWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JB
      VXdBd0VCL3pBZEJnTlZIUTRFCkZnUVU3VTNBeDkwUjlyalhjd1pnQk9qbTRrbjE3UUV3Q2dZSUtv
      Wkl6ajBFQXdJRFNBQXdSUUloQUxCMDVjaTgKMThWaitreDg2cUp6bTdvU0Ivb3l5UDBSN0hrMDR1
      Y1ovSTR6QWlBUm1EVnJhZ1RITEF3bGNkaUZQMW10SmpoZwpEdU9iOVlOczRRbTQ0UEpRYXc9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCgo=
  provider: s3
  s3:
    bucket: cloudnative-pg-backups
    accessKey: om9WSI45aMEZxBqASwSy
    secretKey: f31Tff9m6TaPJRhZ45GjO0HUxzx4yM8HmQ7xCnAJ
  scheduledBackups:
    - name: daily-backup
      schedule: "0 7 0 * * *"
      backupOwnerReference: self
  retentionPolicy: "7d"