apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: immich-immich
  namespace: argocd
spec:
  project: default
  destination:
    namespace: immich
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: immich
      repoURL: 'oci://ghcr.io/immich-app/immich-charts'
      targetRevision: 0.9.3
      helm:
        valueFiles:
        - $values/immich/values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true 