apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: immich-pvc
  namespace: argocd
spec:
  project: default
  destination:
    namespace: immich
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      path: immich/pvc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # automated:
    #   selfHeal: true 