apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  name: minio-tenant-monitor
  namespace: argocd
spec:
  project: default
  destination:
    namespace: minio
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      path: minio/monitors/minio-tenant
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
