apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pve1-ext
  namespace: istio-ingress
spec:
  hosts:
  - "pve1.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  endpoints:
  - address: 192.168.60.2
    ports:
      https: 8006
  # - address: 192.168.60.3
  #   ports:
  #     https: 8006
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pve1-vs
  namespace: istio-ingress
spec:
  hosts:
  - "pve1.local.xuhuisun.com"
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: "pve1.com"
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: pve1
  namespace: istio-ingress
spec:
  host: "pve1.com"
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
    # outlierDetection:
    #   consecutive5xxErrors: 1
    #   interval: 15s
    #   baseEjectionTime: 1m
