apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  name: cert-manager-cluster-issuer
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: cert-manager/issuers
    repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
