apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: priority-class
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      path: terraform/files/priority-class.yaml
  # syncPolicy:
  #   automated:
  #     selfHeal: true