apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  name: vertical-pod-autoscaler
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: vertical-pod-autoscaler
      repoURL: 'https://kubernetes.github.io/autoscaler'
      targetRevision: 0.8.0
      helm:
        valueFiles:
        - $values/vertical-pod-autoscaler/values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  # syncPolicy:
  #   automated:
  #     selfHeal: true
  ignoreDifferences:
    - kind: Secret
      name: vpa-tls-certs
      namespace: kube-system
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key