apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: monitoring
spec:
  hosts:
  - grafana.local.xuhuisun.com
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: lgtm-grafana
        port:
          number: 80