apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: mimir-vs
  namespace: monitoring
spec:
  hosts:
  - mimir.local.xuhuisun.com
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: lgtm-mimir-gateway
        port:
          number: 80
