global:
  storageClass: cstor-csi

auth:
  adminPassword: nIskQiijss

production: true

proxy: edge

replicaCount: 2

podLabels:
  sidecar.istio.io/inject: "true"

postgresql:
  auth:
    postgresPassword: iPdaWcbKq5
    password: u4rmKA7w0q
    replicationPassword: hF7jn7wwhJ
  architecture: replication
