global:
  storageClass: cstor-csi

auth:
  adminPassword: nIskQiijss

production: true

proxyHeaders: xforwarded

replicaCount: 2

podLabels:
  istio.io/dataplane-mode: ambient

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPU: 80

networkPolicy:
  extraIngress:
    - ports:
      - port: 15008

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true

postgresql:
  auth:
    postgresPassword: iPdaWcbKq5
    password: u4rmKA7w0q
    replicationPassword: hF7jn7wwhJ
  architecture: replication
  primary:
    resources:
      requests:
        cpu: 1.5
        memory: 512Mi
      limits:
        cpu: 3
        memory: 1024Mi
  readReplicas:
    resources:
      requests:
        cpu: 1.5
        memory: 512Mi
      limits:
        cpu: 3
        memory: 1024Mi
