global:
  storageClass: cstor-csi

auth:
  adminPassword: nIskQiijss

production: true

proxy: edge

replicaCount: 2

podLabels:
  sidecar.istio.io/inject: "true"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true

postgresql:
  image:
    tag: 15.5.0-debian-11-r15
  auth:
    postgresPassword: iPdaWcbKq5
    password: u4rmKA7w0q
    replicationPassword: hF7jn7wwhJ
  architecture: replication
