global:
  storageClass: cstor-csi

auth:
  adminPassword: nIskQiijss

production: true

proxyHeaders: xforwarded

replicaCount: 2

podLabels:
  sidecar.istio.io/inject: "true"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPU: 80

metrics:
  enabled: true
  service:
    extraPorts:
      - 9000
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true

postgresql:
  image:
    tag: 15.5.0-debian-11-r15
  auth:
    postgresPassword: iPdaWcbKq5
    password: u4rmKA7w0q
    replicationPassword: hF7jn7wwhJ
  architecture: replication
  primary:
    resources:
      requests:
        cpu: 1.5
        memory: 512Mi
      limits:
        cpu: 3
        memory: 1024Mi
  readReplicas:
    resources:
      requests:
        cpu: 1.5
        memory: 512Mi
      limits:
        cpu: 3
        memory: 1024Mi
