priorityClassName: "system-cluster-critical"

resources:
  requests:
    cpu: 12m
    memory: 100Mi
  limits:
    memory: 100Mi

tolerations:
- key: "node-role.kubernetes.io/system"
  operator: "Exists"
  effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/system
              operator: Exists

monitoring:
  podMonitorEnabled: true
  grafanaDashboard:
    create: true