priorityClassName: "system-cluster-critical"

resources:
  requests:
    cpu: 12m
    memory: 100Mi
  limits:
    memory: 100Mi

nodeSelector:
  node-role.kubernetes.io/system: ""

tolerations:
- key: "node-role.kubernetes.io/system"
  operator: "Exists"
  effect: "NoSchedule"

monitoring:
  podMonitorEnabled: true
  grafanaDashboard:
    create: true