resources:
  requests:
    cpu: 12m
    memory: 100Mi
  limits:
    memory: 100Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: karpenter.sh/nodepool
            operator: In
            values: ["system"]
tolerations:
- key: node-role.kubernetes.io/system
  operator: Exists
  effect: NoSchedule
priorityClassName: platform-critical

monitoring:
  podMonitorEnabled: true
  grafanaDashboard:
    create: true