apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: minio-tenant-s3-vs
  namespace: minio
spec:
  hosts:
  - "s3.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: minio
        port:
          number: 80
