apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: minio-tenant-console-vs
  namespace: minio
spec:
  hosts:
  - "minio-console.local.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: myminio-console
        port:
          number: 9443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: minio-tenant-console
  namespace: minio
spec:
  host: myminio-console
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
