apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: minio-tenant-console-vs
  namespace: minio
spec:
  hosts:
  - "minio-console.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: minio-console
        port:
          number: 9443
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: minio-tenant-console-dr
  namespace: minio
spec:
  host: minio-console
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
