apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: istio-base
  namespace: argocd
spec:
  project: default
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    chart: base
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.27.2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jqPathExpressions:
        - .webhooks[] | select(.name == "validation.istio.io") | .failurePolicy
