controller:
  replicas: 2

image:
  repository: ghcr.io/gethomepage/homepage
  tag: v1.4.3

# This enables the service account to access the necessary resources
enableRbac: true

# The service account is necessary to allow discovery of other services
serviceAccount:
  create: true
  name: homepage

podLabels:
  istio.io/dataplane-mode: ambient

config:
  settings:
    title: Homelab Homepage
    background:
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: sm
      saturate: 50
      brightness: 50
      opacity: 50
    theme: dark
    color: slate
  bookmarks:
    - Developer:
        - Github:
            - icon: github-light.png
              href: https://github.com/
        - Gitlab:
            - icon: gitlab.png
              href: https://gitlab.com/
        - Cursor:
            - icon: vscode.png
              href: https://cursor.com/
    - Entertainment:
        - Youtube:
            - icon: youtube.png
              href: https://www.youtube.com/
  services:
    - Network:
        - UniFi:
            icon: unifi-controller.png
            href: https://unifi.ui.com/consoles
            description: network
    - Hypervisor:
        - Proxmox:
            icon: proxmox.png
            href: https://pve2.local-v2.xuhuisun.com
            description: pve2
            siteMonitor: https://192.168.60.3:8006
        - Proxmox Backup Server:
            icon: proxmox.png
            href: https://pbs.local-v2.xuhuisun.com
            description: pbs
            siteMonitor: https://192.168.60.2:8007
    - Remote Access:
        - PVE2 IPMI:
            icon: supermicro.png
            href: https://10.101.2.2
            description: supermicro ipmi
    - Storage:
        - Rook Ceph:
            icon: rook.png
            href: https://rook-ceph.local-v2.xuhuisun.com
            description: rook ceph storage orchestration
            siteMonitor: https://rook-ceph-mgr-dashboard.rook-ceph.svc.cluster.local:8443
        - MinIO:
            icon: minio.png
            href: https://minio-console.local-v2.xuhuisun.com
            description: object storage
            siteMonitor: https://minio-console.minio.svc.cluster.local:9443
        - MinIO Cold Tier:
            icon: minio.png
            href: https://minio-console-cold-tier.local-v2.xuhuisun.com
            description: object storage
            siteMonitor: https://minio-console.minio-cold-tier.svc.cluster.local:9443
    - Home Automation:
        - Scrypted:
            icon: scrypted.png
            href: https://scrypted.local-v2.xuhuisun.com
            description: mgmt console
            siteMonitor: https://10.101.20.221:10443
    - Management:
        - Keycloak:
            icon: keycloak.png
            href: https://keycloak.local-v2.xuhuisun.com
            description: iam
            siteMonitor: http://keycloak-keycloak.keycloak.svc.cluster.local
        - Argo CD:
            icon: argo-cd.png
            href: https://argocd.local-v2.xuhuisun.com
            description: in-cluster cd
            siteMonitor: https://argocd-server.argocd.svc.cluster.local
    - Monitoring:
        - Grafana:
            icon: grafana.png
            href: https://grafana.local-v2.xuhuisun.com
            description: metrics visualization
            siteMonitor: http://lgtm-grafana.monitoring.svc.cluster.local
        - Prometheus:
            icon: prometheus.png
            href: https://prometheus.local-v2.xuhuisun.com
            description: metrics tsdb
            siteMonitor: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        - Mimir:
            icon: prometheus.png
            href: https://mimir.local-v2.xuhuisun.com
            description: tsdb backend
            siteMonitor: http://lgtm-distributed-mimir-nginx.monitoring.svc.cluster.local
        - Kiali:
            href: https://kiali.local-v2.xuhuisun.com
            description: istio mgmt console
            siteMonitor: http://kiali.istio-system.svc.cluster.local:20001
        - Kibana:
            icon: kibana.png
            href: https://kibana.local-v2.xuhuisun.com
            description: elasticsearch visualization
            siteMonitor: https://kibana-kb-http.elastic.svc.cluster.local:5601
    - Productivity:
        - Open-WebUI:
            icon: open-webui.png
            href: https://open-webui.local-v2.xuhuisun.com
            description: ai interface
            siteMonitor: http://open-webui.open-webui.svc.cluster.local
        - Immich:
            icon: immich.png
            href: https://immich.local-v2.xuhuisun.com
            description: photo management/backup
            siteMonitor: http://immich-immich-server.immich.svc.cluster.local:2283
  widgets:
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - datetime:
        format:
          dateStyle: short
          timeStyle: short
          hour12: true
    - search:
        provider: [google]
        target: _blank
    - openmeteo:
        units: imperial
        cache: 5
  kubernetes:
    mode: cluster

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "local-v2.xuhuisun.com,homepage.local-v2.xuhuisun.com"

resources:
  requests:
    cpu: 22m
    memory: 142Mi
  limits:
    memory: 142Mi
