apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: streaming
  namespace: observability
spec:
  strategy: streaming
  collector:
    maxReplicas: 8
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    options:
      kafka:
        producer:
          topic: jaeger-spans
          brokers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  ingester:
    maxReplicas: 8
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    options:
      kafka:
        consumer:
          topic: jaeger-spans
          brokers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  query:
    labels:
      istio.io/dataplane-mode: ambient
  storage:
    dependencies:
      enabled: true
      schedule: "CRON_TZ=America/Los_Angeles 55 23 * * *"
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-es-http.elastic.svc.cluster.local:9200
        index-prefix: jaeger-streaming
        use-aliases: true
    esIndexCleaner:
      enabled: true
      numberOfDays: 7
      schedule: "55 23 * * *"
    esRollover:
      conditions: "{\"max_age\": \"2d\"}"
      readTTL: 168h
      schedule: "55 23 * * *"
  ingress:
    enabled: false
