apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "60"
  name: cnpg
  namespace: argocd
spec:
  project: default
  destination:
    namespace: cnpg-system
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: cloudnative-pg
      repoURL: 'https://cloudnative-pg.github.io/charts'
      targetRevision: 0.25.0
      helm:
        valueFiles:
        - $values/cloudnative-pg/values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true 