apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: csi-driver-nfs
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: csi-driver-nfs
      repoURL: 'https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts'
      targetRevision: 4.12.1
      helm:
        valueFiles:
        - $values/csi-driver-nfs/values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      selfHeal: true