apiVersion: karpenter.proxmox.sinextra.dev/v1alpha1
kind: ProxmoxUnmanagedTemplate
metadata:
  name: talos-worker-template
spec:
  templateName: talos-worker-template
---
apiVersion: karpenter.proxmox.sinextra.dev/v1alpha1
kind: ProxmoxNodeClass
metadata:
  name: default 
spec:
  instanceTemplateRef:
    kind: ProxmoxUnmanagedTemplate
    name: talos-worker-template
  metadataOptions:
    type: cdrom
    templatesRef:
      name: karpenter-template
      namespace: kube-system
  bootDevice:
    size: 50Gi
    storage: local-zfs 
  tags:
    - managed-by_karpenter
    - type_k8s
    - type-k8s-role_node-pool
    - cloned-from_talos-worker-template
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: system
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.proxmox.sinextra.dev
        kind: ProxmoxNodeClass
        name: default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.proxmox.sinextra.dev/instance-family
          operator: In
          values: ["s1"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["s1.2VCPU-8GB", "s1.4VCPU-16GB", "s1.8VCPU-32GB"]
  limits:
    cpu: "64"
    memory: 512Gi
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: user
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.proxmox.sinextra.dev
        kind: ProxmoxNodeClass
        name: default
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: karpenter.proxmox.sinextra.dev/instance-family
          operator: In
          values: ["c1", "s1", "m1"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["c1.2VCPU-4GB", "c1.4VCPU-8GB", "s1.4VCPU-16GB", "s1.8VCPU-32GB", "m1.2VCPU-16GB", "m1.4VCPU-32GB", "m1.8VCPU-64GB"]
  limits:
    cpu: "64"
    memory: 512Gi