apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: platform-critical
value: 100000
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "For platform controllers (Argo CD, ingress controllers, metrics)."