apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: keycloak-vs
  namespace: keycloak
spec:
  hosts:
  - keycloak.local.xuhuisun.com
  - iam.local.xuhuisun.com
  gateways:
  - istio-ingress/gateway
  http:
  - match:
    - authority:
        exact: keycloak.local.xuhuisun.com
    route:
    - destination:
        host: keycloak-keycloak
        port:
          number: 80
  - match:
    - authority:
        exact: iam.local.xuhuisun.com
      uri:
        prefix: /realms/
    - authority:
        exact: iam.local.xuhuisun.com
      uri:
        prefix: /resources/
    - authority:
        exact: iam.local.xuhuisun.com
      uri:
        prefix: /.well-known/
    route:
    - destination:
        host: keycloak-keycloak
        port:
          number: 80
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: keycloak-dr
  namespace: keycloak
spec:
  host: keycloak-keycloak
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: AUTH_SESSION_ID
          ttl: 0s