apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  roles:
    - controller
  resources:
    requests:
      cpu: 1000m
      memory: 4Gi
    limits:
      memory: 4Gi
  storage:
    type: persistent-claim
    size: 1Gi
    deleteClaim: false
    class: ceph-block
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
  annotations:
    strimzi.io/next-node-ids: "[0-99]"
spec:
  replicas: 3
  roles:
    - broker
  resources:
    requests:
      cpu: 2000m
      memory: 8Gi
    limits:
      memory: 8Gi
  storage:
    type: persistent-claim
    size: 10Gi
    deleteClaim: false
    class: ceph-block
