apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
  annotations:
    strimzi.io/next-node-ids: "[100-199]"
spec:
  replicas: 3
  roles:
  - controller
  resources:
    requests:
      cpu: 55m
      memory: 1Gi
    limits:
      memory: 1Gi
  storage:
    type: persistent-claim
    size: 3Gi
    deleteClaim: false
    class: proxmox-local-zfs-xfs
  template:
    pod:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: strimzi.io/pool-name
                    operator: In
                    values:
                      - controller
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
  annotations:
    strimzi.io/next-node-ids: "[0-99]"
spec:
  replicas: 3
  roles:
  - broker
  resources:
    requests:
      cpu: 200m
      memory: 2Gi
    limits:
      memory: 2Gi
  storage:
    type: persistent-claim
    size: 20Gi
    deleteClaim: false
    class: proxmox-local-zfs-xfs
  template:
    pod:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: strimzi.io/pool-name
                    operator: In
                    values:
                      - broker
              topologyKey: "kubernetes.io/hostname"