apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: jaeger-spans
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 8
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
