apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.5.0
    replicas: 5
    resources:
      requests:
        memory: 8Gi
        cpu: "2"
      limits:
        memory: 16Gi
        cpu: "4"
    jvmOptions:
      -Xms: 6g
      -Xmx: 6g
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9092
        type: ingress
        tls: true
        configuration:
          bootstrap:
            host: kafka-bootstrap.local.xuhuisun.com
            annotations:
              kubernetes.io/ingress.class: istio
          brokers:
          - broker: 0
            host: kafka-broker-0.local.xuhuisun.com
            annotations:
              kubernetes.io/ingress.class: istio
          - broker: 1
            host: kafka-broker-1.local.xuhuisun.com
            annotations:
              kubernetes.io/ingress.class: istio
          - broker: 2
            host: kafka-broker-2.local.xuhuisun.com
            annotations:
              kubernetes.io/ingress.class: istio
          - broker: 3
            host: kafka-broker-3.local.xuhuisun.com
            annotations:
              kubernetes.io/ingress.class: istio
          - broker: 4
            host: kafka-broker-4.local.xuhuisun.com
            annotations:
              kubernetes.io/ingress.class: istio
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.5"
    storage:
      type: persistent-claim
      size: 90Gi
      deleteClaim: false
      class: local-device-kafka
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: disktype
                  operator: In
                  values:
                  - ssd
  zookeeper:
    replicas: 5
    resources:
      requests:
        memory: 4Gi
        cpu: "1"
      limits:
        memory: 4Gi
        cpu: "1"
    jvmOptions:
      -Xms: 1g
      -Xmx: 2g
    storage:
      type: persistent-claim
      size: 30Gi
      deleteClaim: false
      class: local-device-zookeeper
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: disktype
                  operator: In
                  values:
                  - ssd
  entityOperator:
    tlsSidecar:
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
