apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-ingress
spec:
  selector:
    istio: istio-ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      credentialName: local-xuhuisun-com-tls
  - port:
      number: 9092
      name: kafka
      protocol: TLS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      credentialName: local-xuhuisun-com-tls
