grafana:
  service:
    ipFamilyPolicy: "PreferDualStack"
    ipFamilies: ["IPv6","IPv4"]
  podLabels:
    istio.io/dataplane-mode: ambient
  resources:
    requests:
      cpu: 76m
      memory: 256Mi
    limits:
      memory: 256Mi
  defaultDashboardsTimezone: America/Los_Angeles
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      7639-istio-mesh-dashboard:
        # renovate: depName="Istio Mesh Dashboard"
        gnetId: 7639
        revision: 259
        datasource: Mimir
      7636-istio-service-dashboard:
        # renovate: depName="Istio Service Dashboard"
        gnetId: 7636
        revision: 259
        datasource: Mimir
      7630-istio-workload-dashboard:
        # renovate: depName="Istio Workload Dashboard"
        gnetId: 7630
        revision: 259
        datasource: Mimir
      11829-istio-performance-dashboard:
        # renovate: depName="Istio Performance Dashboard"
        gnetId: 11829
        revision: 259
        datasource: Mimir
      7645-istio-control-plane-dashboard:
        # renovate: depName="Istio Control Plane Dashboard"
        gnetId: 7645
        revision: 259
        datasource: Mimir
      13277-istio-wasm-extension-dashboard:
        # renovate: depName="Istio Wasm Extension Dashboard"
        gnetId: 13277
        revision: 216
        datasource: Mimir
      13502-minio-dashboard:
        # renovate: depName="MinIO Dashboard"
        gnetId: 13502
        revision: 26
        datasource:
        - name: DS_PROMETHEUS
          value: Mimir
      19237-minio-bucket-dashboard:
        # renovate: depName="MinIO Bucket Dashboard"
        gnetId: 19237
        revision: 2
        datasource:
        - name: DS_PROMETHEUS
          value: Mimir
  grafana.ini:
    server:
      root_url: https://grafana.local-v2.xuhuisun.com
    auth.generic_oauth:
      enabled: true
      name: Keycloak
      allow_sign_up: true
      client_id: grafana
      scopes: "openid email profile offline_access roles"
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      auth_url: "https://iam.local-v2.xuhuisun.com/realms/local-v2/protocol/openid-connect/auth"
      token_url: "https://iam.local-v2.xuhuisun.com/realms/local-v2/protocol/openid-connect/token"
      api_url: "https://iam.local-v2.xuhuisun.com/realms/local-v2/protocol/openid-connect/userinfo"
      role_attribute_path: "contains(resource_access.grafana.roles[*], 'grafanaadmin') && 'GrafanaAdmin' || contains(resource_access.grafana.roles[*], 'admin') && 'Admin' || contains(resource_access.grafana.roles[*], 'editor') && 'Editor' || 'Viewer'"
      groups_attribute_path: groups
      signout_redirect_url: "https://iam.local-v2.xuhuisun.com/realms/local-v2/protocol/openid-connect/logout?post_logout_redirect_uri=https%3A%2F%2Fgrafana.local-v2.xuhuisun.com%2Flogin"
      allow_assign_grafana_admin: true
      use_pkce: true
      use_refresh_token: true
  sidecar:
    dashboards:
      multicluster:
        global:
          enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 118Mi
      limits:
        memory: 118Mi

loki:
  loki:
    schemaConfig:
      configs:
      - from: 2020-09-07
        store: tsdb
        object_store: aws
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
    storageConfig:
      aws:
        s3: https://hU2WB7hZSnLeqP3TU5pm:qGFWTgcXmb0peNqLDSDEV4h8FrxQrjwQBRQDLW5q@minio.minio.svc.cluster.local/loki
        s3forcepathstyle: true
        http_config:
          insecure_skip_verify: true

mimir:
  mimir:
    structuredConfig:
      common:
        storage:
          backend: s3
          s3:
            endpoint: minio.minio.svc.cluster.local
            access_key_id: hU2WB7hZSnLeqP3TU5pm
            secret_access_key: qGFWTgcXmb0peNqLDSDEV4h8FrxQrjwQBRQDLW5q
            http:
              insecure_skip_verify: true
      blocks_storage:
        s3:
          bucket_name: mimir-tsdb
      alertmanager_storage:
        s3:
          bucket_name: mimir-ruler
      ruler_storage:
        s3:
          bucket_name: mimir-ruler
  minio:
    enabled: false

tempo:
  metricsGenerator:
    enabled: true
    config:
      storage:
        remote_write:
        - url: http://{{ .Release.Name  }}-mimir-nginx/api/v1/push
          send_exemplars: true
  storage:
    trace:
      backend: s3
      s3:
        bucket: tempo
        prefix: traces
        endpoint: minio.minio.svc.cluster.local
        tls_insecure_skip_verify: true
        forcepathstyle: true
        access_key: hU2WB7hZSnLeqP3TU5pm
        secret_key: qGFWTgcXmb0peNqLDSDEV4h8FrxQrjwQBRQDLW5q
  # overrides:
  #   defaults:
  #     metrics_generator:
  #       processors:
  #         - service-graphs
  #         - span-metrics
