resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 128Mi

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule