nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule

apiService:
  insecureSkipTLSVerify: false
tls:
  type: cert-manager