resources:
  requests:
    cpu: 10m
    memory: 80Mi
  limits:
    memory: 80Mi

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule