apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-device-zookeeper
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: device
      - name: BlockDeviceSelectors
        data:
          openebs.io/block-device-tag: zookeeper
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
