apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  version: 7.17.12
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  secureSettings:
  - secretName: elastic-secret-settings
  nodeSets:
  - name: masters
    count: 3
    config:
      node.roles: ["master"]
      xpack.ml.enabled: true
      xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
          token:
            enabled: true
          realms.oidc.keycloak:
            order: 2
            rp.client_id: "elastic"
            rp.response_type: code
            rp.redirect_uri: "https://kibana.local.xuhuisun.com/api/security/oidc/callback"
            rp.post_logout_redirect_uri: "https://kibana.local.xuhuisun.com/security/logged_out"
            op.issuer: "https://iam.local.xuhuisun.com/realms/elastic"
            op.authorization_endpoint: "https://iam.local.xuhuisun.com/realms/elastic/protocol/openid-connect/auth"
            op.token_endpoint: "https://iam.local.xuhuisun.com/realms/elastic/protocol/openid-connect/token"
            op.userinfo_endpoint: "https://iam.local.xuhuisun.com/realms/elastic/protocol/openid-connect/userinfo"
            op.endsession_endpoint: "https://iam.local.xuhuisun.com/realms/elastic/protocol/openid-connect/logout"
            op.jwkset_path: "https://iam.local.xuhuisun.com/realms/elastic/protocol/openid-connect/certs"
            claims.principal: email
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: cstor-csi
    podTemplate:
      metadata:
        labels:
          sidecar.istio.io/inject: "true"
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 4Gi
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: disktype
                  operator: In
                  values:
                  - ssd
  - name: data
    count: 5
    config:
      node.roles: ["data", "ingest", "ml", "transform"]
      xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
          token:
            enabled: true
          realms.oidc.keycloak:
            order: 2
            rp.client_id: "elastic"
            rp.response_type: code
            rp.redirect_uri: "https://kibana.local.xuhuisun.com/api/security/oidc/callback"
            rp.post_logout_redirect_uri: "https://kibana.local.xuhuisun.com/security/logged_out"
            op.issuer: "https://iam.local.xuhuisun.com/realms/elastic"
            op.authorization_endpoint: "https://iam.local.xuhuisun.com/realms/elastic/protocol/openid-connect/auth"
            op.token_endpoint: "https://iam.local.xuhuisun.com/realms/elastic/protocol/openid-connect/token"
            op.userinfo_endpoint: "https://iam.local.xuhuisun.com/realms/elastic/protocol/openid-connect/userinfo"
            op.endsession_endpoint: "https://iam.local.xuhuisun.com/realms/elastic/protocol/openid-connect/logout"
            op.jwkset_path: "https://iam.local.xuhuisun.com/realms/elastic/protocol/openid-connect/certs"
            claims.principal: email
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 60Gi
        storageClassName: local-device-elasticsearch
    podTemplate:
      metadata:
        labels:
          sidecar.istio.io/inject: "true"
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 8Gi
              cpu: 2
            limits:
              memory: 8Gi
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: disktype
                  operator: In
                  values:
                  - ssd
