apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 7.17.12
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: elastic
  config:
    server.publicBaseUrl: "https://kibana.local.xuhuisun.com"
    xpack.security.authc.providers:
      oidc.keycloak:
        order: 0
        realm: "elastic"
  podTemplate:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2.5Gi
            cpu: 2
