apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 8.18.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: elastic
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  config:
    server.publicBaseUrl: "https://kibana.local-v2.xuhuisun.com"
  podTemplate:
    metadata:
      labels:
        istio.io/dataplane-mode: ambient
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
          limits:
            memory: 1Gi
