apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: open-webui-vs
  namespace: open-webui
spec:
  hosts:
  - "open-webui.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: open-webui-open-webui
        port:
          number: 80
