apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: heimdall-vs
  namespace: heimdall
spec:
  hosts:
  - "local.xuhuisun.com"
  - "heimdall.local.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: heimdall
        port:
          number: 80
