apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafka-bootstrap-vs
  namespace: kafka
spec:
  hosts:
  - "kafka-bootstrap.local.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  tcp:
  - match:
    - port: 9092
    route:
    - destination:
        host: kafka-cluster-kafka-external-bootstrap
        port:
          number: 9093
