apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kafka-bootstrap-vs
  namespace: kafka
spec:
  hosts:
  - "kafka-bootstrap.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  tcp:
  - match:
    - port: 9092
    route:
    - destination:
        host: kafka-cluster-kafka-external-bootstrap
        port:
          number: 9093
      weight: 100
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kafka-broker-0-vs
  namespace: kafka
spec:
  hosts:
  - "kafka-broker-0.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  tcp:
  - match:
    - port: 9092
    route:
    - destination:
        host: kafka-cluster-kafka-external-0
        port:
          number: 9093
      weight: 100
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kafka-broker-1-vs
  namespace: kafka
spec:
  hosts:
  - "kafka-broker-1.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  tcp:
  - match:
    - port: 9092
    route:
    - destination:
        host: kafka-cluster-kafka-external-1
        port:
          number: 9093
      weight: 100
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kafka-broker-2-vs
  namespace: kafka
spec:
  hosts:
  - "kafka-broker-2.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  tcp:
  - match:
    - port: 9092
    route:
    - destination:
        host: kafka-cluster-kafka-external-2
        port:
          number: 9093
      weight: 100
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kafka-broker-3-vs
  namespace: kafka
spec:
  hosts:
  - "kafka-broker-3.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  tcp:
  - match:
    - port: 9092
    route:
    - destination:
        host: kafka-cluster-kafka-external-3
        port:
          number: 9093
      weight: 100
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kafka-broker-4-vs
  namespace: kafka
spec:
  hosts:
  - "kafka-broker-4.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  tcp:
  - match:
    - port: 9092
    route:
    - destination:
        host: kafka-cluster-kafka-external-4
        port:
          number: 9093
      weight: 100
