apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak-admin-vs
  namespace: keycloak
spec:
  hosts:
  - "keycloak.local.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: keycloak
        port:
          number: 80
