apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak-iam-vs
  namespace: keycloak
spec:
  hosts:
  - "iam.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - match:
    - uri:
        prefix: "/js/"
    - uri:
        prefix: "/realms/"
    - uri:
        prefix: "/resources/"
    - uri:
        prefix: "/robots.txt"
    route:
    - destination:
        host: keycloak
        port:
          number: 80
