apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: minio-tenant-console-vs
  namespace: minio
spec:
  hosts:
  - "minio-console.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: minio-console
        port:
          number: 9090
