apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: pbs-ext
  namespace: istio-ingress
spec:
  hosts:
  - "pbs.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  endpoints:
  - address: 10.101.3.4
    ports:
      https: 8007
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: pbs-vs
  namespace: istio-ingress
spec:
  hosts:
  - "pbs.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: "pbs.com"
        port:
          number: 443
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: pbs-dr
  namespace: istio-ingress
spec:
  host: "pbs.com"
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
    # outlierDetection:
    #   consecutive5xxErrors: 1
    #   interval: 15s
    #   baseEjectionTime: 1m
