apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: pve2-ext
  namespace: istio-ingress
spec:
  hosts:
  - pve2.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  endpoints:
  - address: 10.101.3.3
    ports:
      https: 8006
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: pve2-vs
  namespace: istio-ingress
spec:
  hosts:
  - pve2.local.xuhuisun.com
  gateways:
  - istio-ingress/gateway-http2
  http:
  - route:
    - destination:
        host: pve2.com
        port:
          number: 443
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: pve2-dr
  namespace: istio-ingress
spec:
  host: pve2.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
    # outlierDetection:
    #   consecutive5xxErrors: 1
    #   interval: 15s
    #   baseEjectionTime: 1m