apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rook-ceph-vs
  namespace: rook-ceph
spec:
  hosts:
  - "rook-ceph.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: rook-ceph-mgr-dashboard
        port:
          number: 8443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: rook-ceph-dr
  namespace: rook-ceph
spec:
  host: rook-ceph-mgr-dashboard
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
