apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: scrypted-ext
  namespace: istio-ingress
spec:
  hosts:
  - scrypted.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  endpoints:
  - address: 10.101.20.221
    ports:
      https: 10443
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: scrypted-vs
  namespace: istio-ingress
spec:
  hosts:
  - scrypted.local.xuhuisun.com
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: scrypted.com
        port:
          number: 443
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: scrypted-dr
  namespace: istio-ingress
spec:
  host: scrypted.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true