apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: scrypted-ext
  namespace: istio-ingress
spec:
  hosts:
  - "scrypted.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  endpoints:
  - address: 192.168.20.221
    ports:
      https: 10443
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: scrypted-vs
  namespace: istio-ingress
spec:
  hosts:
  - "scrypted.local-v2.xuhuisun.com"
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: "scrypted.com"
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: scrypted
  namespace: istio-ingress
spec:
  host: "scrypted.com"
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
