apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "79"
  name: ingress-keycloak
  namespace: argocd
spec:
  project: default
  destination:
    namespace: keycloak
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      path: keycloak/ingress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
