global:
  operator:
    replicas: 2
    resources:
      requests:
        cpu: 5m
        memory: 96Mi
      limits:
        memory: 96Mi
    # TODO: tolerations did not work 
    tolerations:
      - key: node-role.kubernetes.io/system
        operator: Exists
        effect: NoSchedule

# operators:
#   minkms:
#     affinity:
#       nodeAffinity:
#         requiredDuringSchedulingIgnoredDuringExecution:
#           nodeSelectorTerms:
#             - matchExpressions:
#               - key: karpenter.sh/nodepool
#                 operator: In
#                 values: ["system"]
#       podAntiAffinity:
#         preferredDuringSchedulingIgnoredDuringExecution:
#           - podAffinityTerm:
#               labelSelector:
#                 matchExpressions:
#                 - key: minkms.min.io/name
#                   operator: In
#                   values:
#                   - minkms-operator
#               topologyKey: topology.kubernetes.io/zone
#             weight: 100
#         requiredDuringSchedulingIgnoredDuringExecution:
#         - labelSelector:
#             matchExpressions:
#             - key: minkms.min.io/name
#               operator: In
#               values:
#               - minkms-operator
#           topologyKey: kubernetes.io/hostname