apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: homepage-vs
  namespace: homepage
spec:
  hosts:
  - "local-v2.xuhuisun.com"
  - "homepage.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: homepage
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: homepage-dr
  namespace: homepage
spec:
  host: homepage
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: User
          ttl: 0s
