apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: homepage-vs
  namespace: homepage
spec:
  hosts:
  - local.xuhuisun.com
  - homepage.local.xuhuisun.com
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: homepage-homepage
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: homepage-dr
  namespace: homepage
spec:
  host: homepage-homepage
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: STICKY_SESSION
          ttl: 0s
          path: /