apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kibana-vs
  namespace: elastic
spec:
  hosts:
  - "kibana.local-v2.xuhuisun.com"
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: kibana-kb-http
        port:
          number: 5601
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: kibana-dr
  namespace: elastic
spec:
  host: kibana-kb-http
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
