apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: minio-tenant-s3-vs
  namespace: minio
spec:
  hosts:
  - s3.local.xuhuisun.com
  gateways:
  - istio-ingress/gateway
  http:
  - route:
    - destination:
        host: minio
        port:
          number: 443
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: minio-tenant-s3-dr
  namespace: minio
spec:
  host: minio
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true