apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: eck-operator
  namespace: argocd
spec:
  project: default
  destination:
    namespace: elastic-system
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: eck-operator
      repoURL: 'https://helm.elastic.co'
      targetRevision: 2.12.1
      helm:
        valueFiles:
        - $values/eck/values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
