apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: elastic
  namespace: argocd
spec:
  project: default
  destination:
    namespace: elastic
    server: 'https://kubernetes.default.svc'
  source:
    path: eck/elastic
    repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
