apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: ingress
  namespace: argocd
spec:
  project: default
  destination:
    namespace: istio-ingress
    server: 'https://kubernetes.default.svc'
  source:
    path: istio/ingress
    repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
