apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: istiod
  namespace: argocd
spec:
  project: default
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: istiod
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.24.1
      helm:
        valueFiles:
        - $values/istio/istiod-values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jqPathExpressions:
        - .webhooks[] | select(.name == "rev.validation.istio.io") | .failurePolicy
