apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: istio-ztunnel
  namespace: argocd
spec:
  project: default
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: ztunnel
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.23.2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
