apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: istio-base
  namespace: argocd
spec:
  project: default
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    chart: base
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.22.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
