apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: istiod
  namespace: argocd
spec:
  project: default
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: istiod
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.23.1
      helm:
        valueFiles:
        - $values/istio/istiod-values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
