apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: istio-cni
  namespace: argocd
spec:
  project: default
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: cni
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.24.0
      helm:
        valueFiles:
        - $values/istio/istio-cni-values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
