apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: prometheus
  namespace: argocd
spec:
  project: default
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: kube-prometheus-stack
      repoURL: 'https://prometheus-community.github.io/helm-charts'
      targetRevision: 65.3.2
      helm:
        valueFiles:
        - $values/kube-prometheus-stack/values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
