apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  name: user-defined-apps
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/applications/user-defined-apps
    repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
