apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-cluster
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  namespaceSelector:
    matchNames:
      - minio
  endpoints:
  - port: https-minio
    path: /minio/v2/metrics/cluster
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: job-name
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-bucket
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  namespaceSelector:
    matchNames:
      - minio
  endpoints:
  - port: https-minio
    path: /minio/v2/metrics/bucket
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: job-name