apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: strimzi-kafka-operator
  namespace: argocd
spec:
  project: default
  destination:
    namespace: strimzi
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: strimzi-kafka-operator
      repoURL: 'https://strimzi.io/charts'
      targetRevision: 0.49.1
      helm:
        valueFiles:
        - $values/strimzi/values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true