apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "41"
  name: keda
  namespace: argocd
spec:
  project: default
  destination:
    namespace: keda
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: keda
      repoURL: 'https://kedacore.github.io/charts'
      targetRevision: 2.17.0
      helm:
        valueFiles:
        - $values/keda/values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
