apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: n8n-cnpg-cluster
  namespace: argocd
spec:
  project: default
  destination:
    namespace: n8n
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: cluster
      repoURL: 'https://cloudnative-pg.github.io/charts'
      targetRevision: 0.5.0
      helm:
        valueFiles:
        - $values/n8n/cnpg-cluster-values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true