apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: n8n-n8n
  namespace: argocd
spec:
  project: default
  destination:
    namespace: n8n
    server: 'https://kubernetes.default.svc'
  sources:
    - path: . 
      repoURL: 'oci://8gears.container-registry.com/library/n8n'
      targetRevision: 2.0.0
      helm:
        valueFiles:
        - $values/n8n/n8n-values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
