apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-xuhuisun-com
  namespace: istio-ingress
spec:
  secretName: local-xuhuisun-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.xuhuisun.com"
  dnsNames:
    - "local.xuhuisun.com"
    - "*.local.xuhuisun.com"
