apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: lgtm-tempo
  namespace: argocd
spec:
  project: default
  destination:
    namespace: monitoring 
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: tempo-distributed
      repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: 1.53.2
      helm:
        valueFiles:
        - $values/lgtm/tempo-values.yaml
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true