apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "43"
  name: ingress-gateway-certificates
  namespace: argocd
spec:
  project: default
  destination:
    namespace: istio-ingress
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/XuhuiSun95/homelab-k8s.git'
      targetRevision: main
      path: istio/certificates/production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
