mimir:
  structuredConfig:
    limits:
      max_global_series_per_user: 10000000
      max_label_names_per_series: 40
      ingestion_rate: 150000
      ingestion_burst_size: 300000
      compactor_blocks_retention_period: 30d
    common:
      storage:
        backend: s3
        s3:
          endpoint: minio.primary-object-store.svc.cluster.local
          access_key_id: X3EEh4lU0Uz9M44FWebq
          secret_access_key: VcqVSaBjrsZhHm8qThNBuzjirzkI3EPB4tQwD5ad
          http:
            insecure_skip_verify: true
    blocks_storage:
      s3:
        bucket_name: mimir-tsdb
    alertmanager_storage:
      s3:
        bucket_name: mimir-ruler
    ruler_storage:
      s3:
        bucket_name: mimir-ruler
    ingest_storage:
      kafka:
        address: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        topic: mimir-ingest
        auto_create_topic_enabled: false
alertmanager:
  persistentVolume:
    size: 1Gi
    storageClass: proxmox-local-zfs-xfs
  replicas: 2
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      memory: 128Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: alertmanager
              app.kubernetes.io/instance: lgtm-mimir
              app.kubernetes.io/name: mimir
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["system"]
  tolerations:
    - key: node-role.kubernetes.io/system
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
compactor:
  persistentVolume:
    size: 5Gi
    storageClass: proxmox-local-zfs-xfs
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 512Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: compactor
              app.kubernetes.io/instance: lgtm-mimir
              app.kubernetes.io/name: mimir
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["system"]
  tolerations:
    - key: node-role.kubernetes.io/system
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
distributor:
  replicas: 2
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      memory: 256Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: distributor
              app.kubernetes.io/instance: lgtm-mimir
              app.kubernetes.io/name: mimir
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["system"]
  tolerations:
    - key: node-role.kubernetes.io/system
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
ingester:
  persistentVolume:
    size: 10Gi
    storageClass: proxmox-local-zfs-xfs
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 1024Mi
    limits:
      memory: 1024Mi
  zoneAwareReplication:
     enabled: false
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: ingester
              app.kubernetes.io/instance: lgtm-mimir
              app.kubernetes.io/name: mimir
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["memory-optimized"]
  tolerations:
    - key: node-role.kubernetes.io/memory-optimized
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
chunks-cache:
  enabled: true
  replicas: 1
  allocatedMemory: 853
  # By default a safe memory limit will be requested based on allocatedMemory value (floor (* 1.2 allocatedMemory)).
  resources:
    requests:
      cpu: 10m
      memory: 1024Mi
    limits:
      memory: 1024Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["memory-optimized"]
  tolerations:
    - key: node-role.kubernetes.io/memory-optimized
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
index-cache:
  enabled: true
  replicas: 1
  allocatedMemory: 426
  # By default a safe memory limit will be requested based on allocatedMemory value (floor (* 1.2 allocatedMemory)).
  resources:
    requests:
      cpu: 20m
      memory: 512Mi
    limits:
      memory: 512Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["memory-optimized"]
  tolerations:
    - key: node-role.kubernetes.io/memory-optimized
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
metadata-cache:
  enabled: true
  replicas: 1
  allocatedMemory: 106
  # By default a safe memory limit will be requested based on allocatedMemory value (floor (* 1.2 allocatedMemory)).
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 128Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["memory-optimized"]
  tolerations:
    - key: node-role.kubernetes.io/memory-optimized
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
memcachedExporter:
  resources:
    requests:
      cpu: 5m
      memory: 16Mi
    limits:
      memory: 16Mi
results-cache:
  enabled: true
  replicas: 1
  allocatedMemory: 213
  # By default a safe memory limit will be requested based on allocatedMemory value (floor (* 1.2 allocatedMemory)).
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 256Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["memory-optimized"]
  tolerations:
    - key: node-role.kubernetes.io/memory-optimized
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
minio:
  enabled: false
kafka:
  enabled: false
overrides_exporter:
  replicas: 1
  resources:
    requests:
      cpu: 5m
      memory: 32Mi
    limits:
      memory: 32Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: overrides-exporter
              app.kubernetes.io/instance: lgtm-mimir
              app.kubernetes.io/name: mimir
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["system"]
  tolerations:
    - key: node-role.kubernetes.io/system
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
querier:
  replicas: 1
  resources:
    requests:
      cpu: 80m
      memory: 1024Mi
    limits:
      memory: 1024Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: querier
              app.kubernetes.io/instance: lgtm-mimir
              app.kubernetes.io/name: mimir
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["memory-optimized"]
  tolerations:
    - key: node-role.kubernetes.io/memory-optimized
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
query_frontend:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 256Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: query-frontend
              app.kubernetes.io/instance: lgtm-mimir
              app.kubernetes.io/name: mimir
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["system"]
  tolerations:
    - key: node-role.kubernetes.io/system
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
query_scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      memory: 128Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: query-scheduler
              app.kubernetes.io/instance: lgtm-mimir
              app.kubernetes.io/name: mimir
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["system"]
  tolerations:
    - key: node-role.kubernetes.io/system
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
ruler:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 256Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: ruler
              app.kubernetes.io/instance: lgtm-mimir
              app.kubernetes.io/name: mimir
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["system"]
  tolerations:
    - key: node-role.kubernetes.io/system
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
store_gateway:
  persistentVolume:
    size: 2Gi
    storageClass: proxmox-local-zfs-xfs
  replicas: 3
  resources:
    requests:
      cpu: 50m
      memory: 1024Mi
    limits:
      memory: 1024Mi
  zoneAwareReplication:
     enabled: false
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: store-gateway
              app.kubernetes.io/instance: lgtm-mimir
              app.kubernetes.io/name: mimir
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["memory-optimized"]
  tolerations:
    - key: node-role.kubernetes.io/memory-optimized
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
gateway:
  replicas: 1
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      memory: 64Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: gateway
              app.kubernetes.io/instance: lgtm-mimir
              app.kubernetes.io/name: mimir
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["system"]
  tolerations:
    - key: node-role.kubernetes.io/system
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical

rollout_operator:
  resources:
    requests:
      cpu: 5m
      memory: 64Mi
    limits:
      memory: 64Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key:  karpenter.sh/nodepool
              operator: In
              values: ["system"]
  tolerations:
    - key: node-role.kubernetes.io/system
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical