crds:
  enabled: true

replicaCount: 2

dns01RecursiveNameservers: "1.1.1.1:53,8.8.8.8:53"

dns01RecursiveNameserversOnly: true

serviceIPFamilyPolicy: "PreferDualStack"

serviceIPFamilies: ["IPv6","IPv4"]

podDnsPolicy: "ClusterFirst"

podDnsConfig:
  nameservers:
    - "1.1.1.1"
    - "8.8.8.8"
